// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0--rc2
// source: agent.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatagentClient is the client API for Datagent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatagentClient interface {
	// Get data from data agent.
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type datagentClient struct {
	cc grpc.ClientConnInterface
}

func NewDatagentClient(cc grpc.ClientConnInterface) DatagentClient {
	return &datagentClient{cc}
}

func (c *datagentClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/agent.Datagent/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatagentServer is the server API for Datagent service.
// All implementations must embed UnimplementedDatagentServer
// for forward compatibility
type DatagentServer interface {
	// Get data from data agent.
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	mustEmbedUnimplementedDatagentServer()
}

// UnimplementedDatagentServer must be embedded to have forward compatible implementations.
type UnimplementedDatagentServer struct {
}

func (UnimplementedDatagentServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDatagentServer) mustEmbedUnimplementedDatagentServer() {}

// UnsafeDatagentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatagentServer will
// result in compilation errors.
type UnsafeDatagentServer interface {
	mustEmbedUnimplementedDatagentServer()
}

func RegisterDatagentServer(s grpc.ServiceRegistrar, srv DatagentServer) {
	s.RegisterService(&Datagent_ServiceDesc, srv)
}

func _Datagent_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatagentServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Datagent/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatagentServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Datagent_ServiceDesc is the grpc.ServiceDesc for Datagent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datagent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Datagent",
	HandlerType: (*DatagentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Datagent_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
